### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by ghost** [FellishBeast/CarnivorousRex#2]
different sounds for eating meat

**Comment by FellishBeast** [comment]
dumb idea please uninstall

**Comment by FellishBeast** [comment]
im thinkin bout it again and i realized it is just really really ! dumb. please stop.

**Comment by FellishBeast** [comment]
du mb

**Comment by genericidentity** [comment]
You hurt my feeling bads

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ghost** [comment]
you hurt my feeling bads
